apiVersion: v1
kind: Pod
metadata:
      name: data1
      labels:
        name: db
spec:
   containers:
     - name: data
       image: mysql
       resources:
              requests:
                  memory: "200M"
                  cpu: "200m"
              limits:
                  memory: "200M"
                  cpu: "200m"
       env:
         - name: MYSQL_ROOT_PASSWORD
           value: admin
