apiVersion: v1
kind: Pod
metadata:
      name: web2
      labels:
        name: xyz
spec:
   containers:
     - name: web2
       image: nginx
       resources:
               requests:
                    memory: "500M"
                    cpu: "500m"
               limits:
                    memory: "500M"
                    cpu: "500m"
