apiVersion: v1 
kind: ReplicationController
metadata:
      name: web-app-rc
spec:
     template:
        metadata: 
              name: web2
              labels:
                name: xyz
        spec: 
          containers:
            - name: web
              image: nginx
     selector: 
         name: xyz
     replicas: 2
