apiVersion: apps/v1 
kind: ReplicaSet
metadata:
      name: web-app-rs
spec:
     template:
        metadata: 
              name: web2
              labels:
                name: xyz
        spec: 
          containers:
            - name: web
              image: nginx
     selector: 
       matchLabels:
          name: xyz
     replicas: 2
